BackendBundle\Entity\Users:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacio"}
        surname:
            - NotBlank: {message: "Los apellidos no pueden estar vacios"}
        nick:
            - NotBlank: {message: "El nick no puede estar vacio"}
        email:
            - Email: 
                message: El email {{ value }} no es valido.
                checkMX: false